from CasosDeUso import CasoDeUso, Flujo, FlujoAlterno

casos_de_uso = [
    CasoDeUso(
        titulo="Crear Usuario",
        actores="Administrador",
        tipo="Primario",
        requisitos="RF-2",
        casoDeUso="",
        precondicion="El nombre de usuario no debe pertenecer a un usuario existente",
        postcondicion="El usuario se habrá creado correctamente",
        proposito="Crear un nuevo usuario",
        resumen="Un administrador creará un nuevo usuario desde el panel de administración",
        flujo=[
            Flujo('1','Administrador: Accede al panel de administración','',''),
            Flujo('2','Administrador: Selecciona la creación de un nuevo y rellena los datos que se le solicitan','',''),
            Flujo('','','3','Se comprueba que el nombre de usuario sea válido'),
            Flujo('','','4','Se crea un nuevo usuario en la base de datos'),
            Flujo('5','Administrador: Recibe una respuesta existosa','',''),
        ],
        flujoAlterno=[
            FlujoAlterno('3a','Si ya existe un usuario con el nombre de usuario especificado se devolverá un error')
        ],
        frecuencia="Muy Baja",
        rendimiento="Alta",
        importancia="Alta",
        urgencia="Alta",
        estado="Realizado",
        estabilidad="Alta",
        comentarios=""
    ),
    CasoDeUso(
        titulo="Eliminar Usuario",
        actores="Administrador",
        tipo="Primario",
        requisitos="RF-3",
        casoDeUso="CU-7, CU-11, CU-14",
        precondicion="El usuario existe en el sistema",
        postcondicion="El usuario se habrá borrado del sistema",
        proposito="Borrar un usuario existente",
        resumen="El administrador borrará un usuario existente desde el panel de administración",
        flujo=[
            Flujo('1','Administrador: Accede al panel de administración','',''),
            Flujo('2','Administrador: Selecciona la la eliminación de un usuario','',''),
            Flujo('','','3','Se borran los recursos asociados al usuario (datasets, modelos y clasificaciones)'),
            Flujo('','','4','Se elimina al usuario de la base de datos'),
            Flujo('5','Administrador: Recibe una respuesta existosa','',''),
        ],
        flujoAlterno=[
            FlujoAlterno('','')
        ],
        frecuencia="Muy baja",
        rendimiento="Alta",
        importancia="Media",
        urgencia="Baja",
        estado="Realizado",
        estabilidad="Alta",
        comentarios=""
    ),
    CasoDeUso(
        titulo="Iniciar sesión",
        actores="Visitante, Usuario(Secundario)",
        tipo="Primario",
        requisitos="RF-4, RF-5",
        casoDeUso="",
        precondicion="El usuario no está autenticado en el sistema",
        postcondicion="El rol del actor pasará a ser Usuario",
        proposito="Iniciar sesión en la aplicación",
        resumen="Un visitante iniciará sesión en el sistema con una cuenta existente",
        flujo=[
            Flujo('1','Visitante: Entrará a la página de inicio de sesión','',''),
            Flujo('2','Visitante: Introducirá sus datos de usuario en el formulario','',''),
            Flujo('','','3','Se valida que el nombre de usuario y contraseña sean correctos'),
            Flujo('','','4','Se guarda el token de sesión en el cliente'),
            Flujo('5','Usuario: Se redirigirá a la pantalla de inicio del usuario','',''),
        ],
        flujoAlterno=[
            FlujoAlterno('3a','Si el nombre de usuario o contraseña no son válidos se devolverá un error al usuario y se mantendrá en la página de inicio de sesión')
        ],
        frecuencia="Baja",
        rendimiento="Alto",
        importancia="Alta",
        urgencia="Alta",
        estado="Realizado",
        estabilidad="Alta",
        comentarios="El token de autenticación se guardará en el cliente, permitiendo al usuario mantener su sesión iniciada sin tener que repetir el proceso cada vez"
    ),
    CasoDeUso(
        titulo="Modificar Contraseña",
        actores="Usuario",
        tipo="Primario",
        requisitos="RF-20",
        casoDeUso="",
        precondicion="",
        postcondicion="La contraseña del usuario se habrá actualizado en la base de datos",
        proposito="Modificar la contraseña del usuario",
        resumen="Un usuario podrá modificar su contraseña desde la página de usuario",
        flujo=[
            Flujo('1','Usuario: Entrará al panel de gestión de usuario','',''),
            Flujo('2','Usuario: Rellenará el formulario de cambio de contraseña especificando su contraseña actual y la contraseá nueva','',''),
            Flujo('','','3','Se valida que la contraseña proporcionada sea correcta'),
            Flujo('','','4','Se modifica la contraseña del usuario en la base de datos'),
            Flujo('5','Usuario: Recibirá una respuesta exitosa del sistema','',''),
        ],
        flujoAlterno=[
            FlujoAlterno('3a','Si la contraseña actual proporcionada no es correcta se devolverá un mensaje de error al usuario')
        ],
        frecuencia="Muy baja",
        rendimiento="Alta",
        importancia="Alta",
        urgencia="Baja",
        estado="Realizado",
        estabilidad="Alta",
        comentarios=""
    ),
    CasoDeUso(
        titulo="Cerrar Sesión",
        actores="Usuario, Visitante(Secundario)",
        tipo="Primario",
        requisitos="RF-6",
        casoDeUso="",
        precondicion="",
        postcondicion="El rol del actor pasará a ser Visitante",
        proposito="Permitir cerrar sesión al Usuario",
        resumen="El usuario cerrará sesión en la aplicación",
        flujo=[
            Flujo('1','Usuario: Interactuará con el botón de cierre de sesión','',''),
            Flujo('','','2','Se borrará del cliente el token de autenticación'),
            Flujo('','','3','Se invalidará el token de autenticación en la base de datos'),
            Flujo('4','Visitante: Se le redigirá a la página de inicio de sesión','',''),
        ],
        flujoAlterno=[
            FlujoAlterno('','')
        ],
        frecuencia="Baja",
        rendimiento="Alto",
        importancia="Alta",
        urgencia="Baja",
        estado="Realizado",
        estabilidad="Alta",
        comentarios="El token de autenticación se borrará del cliente"
    ),
    CasoDeUso(
        titulo="Subir Dataset",
        actores="Usuario",
        tipo="Primario",
        requisitos="RF-7, RF-8, RNF-2",
        casoDeUso="",
        precondicion="El usuario no tiene subido ese dataset en el sistema",
        postcondicion="Se subirá el dataset al sistema",
        proposito="El usuario podrá subir un dataset al sistema",
        resumen="El usuario seleccionará subir un nuevo dataset al sistema, ya sea desde un fichero local o cargando el dataset desde HuggingFace",
        flujo=[
            Flujo('1','Usuario: Seleccionará añadir un nuevo dataset','',''),
            Flujo('2','Usuario: Seleccionará el dataset que quiera subir','',''),
            Flujo('','','3','Se creará una nueva entrada en la base de datos con el dataset creado'),
            Flujo('4','Usuario: Recibirá una respuesta exitosa','',''),
        ],
        flujoAlterno=[
            FlujoAlterno('2a','El usuario podrá subir el dataset desde un fichero local, pudiendo marcar este como privado'),
            FlujoAlterno('2b','El usuario podrá buscar un dataset existente en HuggingFace y subirlo al sistema'),
            FlujoAlterno('3a','Si el dataset se ha cargado desde un fichero local se guardará en el servidor'),
        ],
        frecuencia="Media",
        rendimiento="Medio",
        importancia="Alta",
        urgencia="Alta",
        estado="Realizado",
        estabilidad="Alta",
        comentarios=""
    ),
    CasoDeUso(
        titulo="Borrar Dataset",
        actores="Usuario Propietario, Administrador",
        tipo="Primario",
        requisitos="RF-15",
        casoDeUso="CU-02, CU-14",
        precondicion="El dataset tiene que existir en el sistema",
        postcondicion="El dataset se borrará del sistema",
        proposito="Borrar un dataset de un usuario",
        resumen="Un usuario o administrador podrá borrar un dataset existente en el sistema",
        flujo=[
            Flujo('1','Usuario: Seleccionará el dataset a borrar y se le solicitará confirmación antes de borrarlo','',''),
            Flujo('','','2','Se borrarán las clasificaciones asociadas al dataset'),
            Flujo('','','3','Se borrarán los ficheros físicos asociados al dataset'),
            Flujo('','','4','Se borrará el dataset de la base de datos'),
            Flujo('5','Usuario: Recibirá una respuesta exitosa','',''),
        ],
        flujoAlterno=[
            FlujoAlterno('',''),
        ],
        frecuencia="Baja",
        rendimiento="Alto",
        importancia="Alta",
        urgencia="Media",
        estado="Realizado",
        estabilidad="Alta",
        comentarios=""
    ),
    CasoDeUso(
        titulo="Listar datasets de un usuario",
        actores="Usuario",
        tipo="Primario",
        requisitos="RF-11, RF-12",
        casoDeUso="",
        precondicion="El usuario del que se quieren listar los datasets debe existir",
        postcondicion="",
        proposito="Mostrar el listado de datasets que ha subido un usuario",
        resumen="Un usuario podrá ver el listado de datasets de cualquier usuario, siempre que sean públicos o sea propietario.",
        flujo=[
            Flujo('1','Usuario: Seleccionará ver los datasets de un usuario en concreto','',''),
            Flujo('','','2','Se comprobará que el usuario que ha solicitado los datasets es administrador o propietario'),
            Flujo('','','3','Se obtendrán de la base de datos la lista de datasets relacionados con el usuario objetivo a los que el usuario solicitante tiene permiso'),
            Flujo('4','Usuario: Recibirá una lista de datasets que ha subido el usuario especificado','',''),
        ],
        flujoAlterno=[
            FlujoAlterno('4a','Si el usuario es administrador o es el propietario de los datasets, la lista de datasets incluirá una opción para borrarlos del sistema'),
        ],
        frecuencia="Alta",
        rendimiento="Alto",
        importancia="Alta",
        urgencia="Alta",
        estado="Realizado",
        estabilidad="Alta",
        comentarios=""
    ),
    CasoDeUso(
        titulo="Inspeccionar Dataset",
        actores="Usuario",
        tipo="Primario",
        requisitos="RF-11, RF-12",
        casoDeUso="CU-13",
        precondicion="El dataset debe existir en el sistema",
        postcondicion="",
        proposito="Mostrar la información de un dataset",
        resumen="Un usuario podrá ver la información relativa a un dataset, una pequeña previsualización de los datos y la lista de clasificaciones realizadas a ese dataset",
        flujo=[
            Flujo('1','Usuario: Accederá a la visualización de un dataset','',''),
            Flujo('','','2','Se comprobará si el usuario tiene permisos para acceder al dataset'),
            Flujo('','','3','Se obtendrá la información relacionada al dataset de la base de datos'),
            Flujo('','','4','Se obtendrá una previsualización de los datos del dataset'),
            Flujo('','','5','Se obtendrá la lista de clasificaciones realizadas al dataset'),
            Flujo('6','Usuario: Recibirá la información relacionada con el dataset','',''),
        ],
        flujoAlterno=[
            FlujoAlterno('2a','Si el dataset es privado y el usuario no es el propietario ni administrador, se devolverá un error de permisos'),
        ],
        frecuencia="Alta",
        rendimiento="Medio",
        importancia="Alta",
        urgencia="Media",
        estado="Realizado",
        estabilidad="Alta",
        comentarios=""
    ),
    CasoDeUso(
        titulo="Subir Modelo",
        actores="Usuario",
        tipo="Primario",
        requisitos="RF-9, RNF-3",
        casoDeUso="",
        precondicion="El modelo debe existir en HuggingFace y el usuario no debe haber subido ya ese modelo al sistema",
        postcondicion="Se añadirá el modelo al sistema",
        proposito="Permitir al usuario subir un modelo de clasificación al sistema",
        resumen="El usuario subirá un modelo al sistema. Para ello podrá buscar en HuggingFace un modelo existente y seleccionarlo.",
        flujo=[
            Flujo('1','Usuario: Seleccionará añadir un nuevo modelo','',''),
            Flujo('2','Usuario: Introducirá el nombre del modelo en el campo de búsqueda','',''),
            Flujo('','','3','El sistema buscará los modelos que tengan ese nombre en HHuggingFace'),
            Flujo('4','Usuario: recibirá una lista con los modelos que contienen el nombre buscado','',''),
            Flujo('5','Usuario: Seleccionará uno de los modelos','',''),
            Flujo('','','6','El sistema guardará el modelo seleccionado en el sistema'),
            Flujo('7','Usuario: Recibirá una respuesta existosa','',''),
        ],
        flujoAlterno=[
            FlujoAlterno('3a','Si no se encuentra ningún modelo con el nombre proporcionado el sistema informará de ello al usuario y volverá al paso 2'),
            FlujoAlterno('6a','Si el modelo ya está subido en el sistema por el usuario se devolverá un mensaje de error al usuario'),
        ],
        frecuencia="Media",
        rendimiento="Alto",
        importancia="Alta",
        urgencia="Alta",
        estado="Realizado",
        estabilidad="Alta",
        comentarios=""
    ),
    CasoDeUso(
        titulo="Borrar Modelo",
        actores="Usuario",
        tipo="Primario",
        requisitos="RF-16-RF-19",
        casoDeUso="CU-02",
        precondicion="El modelo debe existir en el sistema",
        postcondicion="Se borrará el modelo del sistema",
        proposito="Permitir al usuario borrar los modelos",
        resumen="Un usuario o administrador podrá borrar un dataset existente en el sistema",
        flujo=[
            Flujo('1','Usuario: Seleccionará el modelo a borrar y se le solicitará confirmación antes de borrarlo','',''),
            Flujo('','','2','Se borrará el modelo de la base de datos'),
            Flujo('3','Usuario: Recibirá una respuesta exitosa','',''),
        ],
        flujoAlterno=[
            FlujoAlterno('',''),
        ],
        frecuencia="Baja",
        rendimiento="Alta",
        importancia="Alta",
        urgencia="Baja",
        estado="Realizado",
        estabilidad="Alta",
        comentarios=""
    ),
    CasoDeUso(
        titulo="Listar Modelos",
        actores="Usuario",
        tipo="Primario",
        requisitos="RF-13",
        casoDeUso="",
        precondicion="El usuario del que se quieren listar los datasets debe existir",
        postcondicion="",
        proposito="Mostrar el listado de modelos que ha subido un usuario.",
        resumen="Un usuario podrá ver el listado de modelos de cualquier usuario.",
        flujo=[
            Flujo('1','Usuario: Seleccionará ver los modelos de un usuario en concreto','',''),
            Flujo('','','2','Se obtendrán de la base de datos la lista de modelos subidos por el usuario objetivo'),
            Flujo('3','Usuario: Recibirá una lista de modelos que ha subido el usuario especificado','',''),
        ],
        flujoAlterno=[
            FlujoAlterno('',''),
        ],
        frecuencia="Alta",
        rendimiento="Alto",
        importancia="Alta",
        urgencia="Alta",
        estado="Realizado",
        estabilidad="Alta",
        comentarios=""
    ),
    CasoDeUso(
        titulo="Realizar Clasificación",
        actores="Usuario Propietario, Administrador",
        tipo="Primario",
        requisitos="RF-10, RF-13, RNF-4",
        casoDeUso="",
        precondicion="El dataset al que se quiere realizar la clasificación debe existir en el sistema",
        postcondicion="Se creará una tarea para ejecutar la clasificación",
        proposito="Clasificar un dataset",
        resumen="Un usuario podrá ejecutar una clasificación de la que sea propietario",
        flujo=[
            Flujo('1','Usuario: Seleccionará realizar una nueva clasificación de un dataset.','',''),
            Flujo('','','2','El sistema obtendrá todos los modelos subidos por el usuario.'),
            Flujo('','','3','El sistema obtendrá todos los nombres de las columnas del dataset.'),
            Flujo('4','Usuario: Irá seleccionando los parámetros de la clasificación de uno en uno hasta que seleccione la columna en la que se encuentran las clases del dataset.','',''),
            Flujo('','','5','El sistema obtendrá los valores diferentes de esa columna y le permitirá al usuario escribir una descripción por cada clase.'),
            Flujo('6','Usuario: Seleccionará el resto de parámetros de la clasificación.','',''),
            Flujo('','','7','El sistema guardará la clasificación en la base de datos y pondrá la tarea en cola para que el gestor de tareas en background la procese cuando esté disponible'),
            Flujo('8','Usuario: Recibirá una respuesta exitosa del sistema.','',''),
            Flujo('','','9','El gestor de colas obtendrá la tarea de la cola y actualizará el estado de la clasificación.'),
            Flujo('','','10','Una vez terminada la clasificación, se guardará el resultado en disco y se actualizará el estado en la base de datos.'),
        ],
        flujoAlterno=[
            FlujoAlterno('5a','Si la columna seleccionada tiene demasiados valores diferentes se pedirá al usuario que seleccione otra.'),
        ],
        frecuencia="Media",
        rendimiento="Bajo",
        importancia="Alta",
        urgencia="Alta",
        estado="Realizado",
        estabilidad="Alta",
        comentarios="La creación de la clasificación, la puesta en cola y la respuesta al usuario deben ser rápidas, pero el tiempo que tarde en realizarse la clasificación dependerá del número de datos con los que se quiera realizar la clasificación."
    ),
    CasoDeUso(
        titulo="Borrar Clasificación",
        actores="Usuario Propietario, Administrador",
        tipo="Primario",
        requisitos="RF-17, RF-19",
        casoDeUso="CU-02",
        precondicion="La clasificación tiene que existir en el sistema",
        postcondicion="La clasificación se borrará del sistema",
        proposito="Borrar una clasificación de un usuario",
        resumen="Un usuario o administrador podrá borrar una clasificación existente en el sistema",
        flujo=[
            Flujo('1','Usuario: Seleccionará la clasificación a borrar y se le solicitará confirmación antes de borrarlo','',''),
            Flujo('','','2','Se borrarán los ficheros físicos asociados a la clasificación'),
            Flujo('','','3','Se borrará la clasificación de la base de datos'),
            Flujo('4','Usuario: Recibirá una respuesta exitosa','',''),
        ],
        flujoAlterno=[
            FlujoAlterno('',''),
        ],
        frecuencia="Baja",
        rendimiento="Alto",
        importancia="Alta",
        urgencia="Baja",
        estado="Realizado",
        estabilidad="Alta",
        comentarios=""
    ),
    CasoDeUso(
        titulo="Listar Clasificaciones de un usuario",
        actores="Usuario",
        tipo="Primario",
        requisitos="RF-14",
        casoDeUso="",
        precondicion="El usuario del que se quieren listar las clasificaciones debe existir",
        postcondicion="",
        proposito="Mostrar el listado de clasificaciones que ha subido un usuario",
        resumen="Un usuario podrá ver el listado de clasificaciones de cualquier usuario, siempre que sean clasificaciones de datasets públicos o sea propietario",
        flujo=[
            Flujo('1','Usuario: Seleccionará ver las clasificaciones de un usuario en concreto','',''),
            Flujo('','','2','Se comprobará que el usuario que ha solicitado las clasificaciones es administrador o es propietario de las clasificaciones solicitadas'),
            Flujo('','','3','Se obtendrán de la base de datos la lista de clasificaciones relacionados con el usuario objetivo a los que el usuario solicitante tiene permiso'),
            Flujo('4','Usuario: Recibirá una lista de clasificaciones que ha subido el usuario especificado','',''),
        ],
        flujoAlterno=[
            FlujoAlterno('',''),
        ],
        frecuencia="Alta",
        rendimiento="Alto",
        importancia="Alta",
        urgencia="Media",
        estado="Realizado",
        estabilidad="Alta",
        comentarios=""
    ),
    CasoDeUso(
        titulo="Listar Clasificaciones de un dataset",
        actores="Usuario",
        tipo="Primario",
        requisitos="RF-14",
        casoDeUso="CU-09",
        precondicion="El dataset del que se quieren listar las clasificaciones debe existir",
        postcondicion="",
        proposito="Mostrar el listado de clasificaciones realizadas a un dataset",
        resumen="Un usuario podrá ver el listado de clasificaciones de cualquier dataset",
        flujo=[
            Flujo('1','Usuario: Seleccionará ver las clasificaciones de un dataset en concreto','',''),
            Flujo('','','2','Se comprobará que el usuario que ha solicitado las clasificaciones es administrador o es propietario de las clasificaciones solicitadas'),
            Flujo('','','3','Se obtendrán de la base de datos la lista de clasificaciones relacionados con el dataset objetivo'),
            Flujo('4','Usuario: Recibirá una lista de clasificaciones realizadas al dataset','',''),
        ],
        flujoAlterno=[
            FlujoAlterno('2a','Si el usuario no tiene permiso para ver el dataset se devolverá un mensaje de error al usuario.'),
        ],
        frecuencia="Alta",
        rendimiento="Alto",
        importancia="Alta",
        urgencia="Media",
        estado="Realizado",
        estabilidad="Alta",
        comentarios=""
    ),
    CasoDeUso(
        titulo="Ver Resultados de una clasificación",
        actores="Usuario",
        tipo="Primario",
        requisitos="RF-14",
        casoDeUso="",
        precondicion="La clasificación tiene que existir en el sistema",
        postcondicion="",
        proposito="Ver el estado, los parametros y los resultados de una clasificación.",
        resumen="Un usuario accederá a los resultados de una clasificación, donde podrá observar los parámetros con los que se ha realizado, el estado actual y los resultados obtenidos.",
        flujo=[
            Flujo('1','Usuario: Accederá a la visualización de una clasificación','',''),
            Flujo('','','2','Se comprobará si el usuario tiene permisos para acceder a la clasificación'),
            Flujo('','','3','Se obtendrá la información relacionada a la clasificación de la base de datos'),
            Flujo('','','4','Se obtendrá de disco el resultado si la clasificación ha terminado'),
            Flujo('5','Usuario: Recibirá la información relacionada con la clasificación','',''),
        ],
        flujoAlterno=[
            FlujoAlterno('2a','Si el dataset asociado es privado y el usuario no es el propietario ni administrador, se devolverá un error de permisos'),
        ],
        frecuencia="Alta",
        rendimiento="Medio",
        importancia="Alta",
        urgencia="Media",
        estado="Realizado",
        estabilidad="Alta",
        comentarios=""
    ),
]
