from CasosDeUso import CasoDeUso, Flujo, FlujoAlterno

casos_de_uso = [
    CasoDeUso(
        titulo="Crear Usuario",
        actores="Administrador",
        tipo="Primario",
        requisitos="RF-2",
        casoDeUso="",
        precondicion="El nombre de usuario no debe pertenecer a un usuario existente",
        postcondicion="El usuario se habrá creado correctamente",
        proposito="Crear un nuevo usuario",
        resumen="Un administrador creará un nuevo usuario desde el panel de administración",
        flujo=[
            Flujo('1','Administrador: Accede al panel de administración','',''),
            Flujo('2','Administrador: Selecciona la creación de un nuevo y rellena los datos que se le solicitan','',''),
            Flujo('','','3','Se comprueba que el nombre de usuario sea válido'),
            Flujo('','','4','Se crea un nuevo usuario en la base de datos'),
            Flujo('5','Administrador: Recibe una respuesta existosa','',''),
        ],
        flujoAlterno=[
            FlujoAlterno('3a','Si ya existe un usuario con el nombre de usuario especificado se devolverá un error')
        ],
        frecuencia="Muy Baja",
        rendimiento="Alta",
        importancia="Alta",
        urgencia="Alta",
        estado="Realizado",
        estabilidad="Alta",
        comentarios=""
    ),
    CasoDeUso(
        titulo="Eliminar Usuario",
        actores="Administrador",
        tipo="Primario",
        requisitos="RF-3",
        casoDeUso="CU-7, CU-11, CU-14",
        precondicion="El usuario existe en el sistema",
        postcondicion="El usuario se habrá borrado del sistema",
        proposito="Borrar un usuario existente",
        resumen="El administrador borrará un usuario existente desde el panel de administración",
        flujo=[
            Flujo('1','Administrador: Accede al panel de administración','',''),
            Flujo('2','Administrador: Selecciona la la eliminación de un usuario','',''),
            Flujo('','','3','Se borran los recursos asociados al usuario (datasets, modelos y clasificaciones)'),
            Flujo('','','4','Se elimina al usuario de la base de datos'),
            Flujo('5','Administrador: Recibe una respuesta existosa','',''),
        ],
        flujoAlterno=[
            FlujoAlterno('','')
        ],
        frecuencia="Muy baja",
        rendimiento="Alta",
        importancia="Media",
        urgencia="Baja",
        estado="Realizado",
        estabilidad="Alta",
        comentarios=""
    ),
    CasoDeUso(
        titulo="Iniciar sesión",
        actores="Visitante, Usuario(Secundario)",
        tipo="Primario",
        requisitos="RF-4, RF-5",
        casoDeUso="",
        precondicion="El usuario no está autenticado en el sistema",
        postcondicion="El rol del actor pasará a ser Usuario",
        proposito="Iniciar sesión en la aplicación",
        resumen="Un visitante iniciará sesión en el sistema con una cuenta existente",
        flujo=[
            Flujo('1','Visitante: Entrará a la página de inicio de sesión','',''),
            Flujo('2','Visitante: Introducirá sus datos de usuario en el formulario','',''),
            Flujo('','','3','Se valida que el nombre de usuario y contraseña sean correctos'),
            Flujo('','','4','Se guarda el token de sesión en el cliente'),
            Flujo('5','Usuario: Se redirigirá a la pantalla de inicio del usuario','',''),
        ],
        flujoAlterno=[
            FlujoAlterno('3a','Si el nombre de usuario o contraseña no son válidos se devolverá un error al usuario y se mantendrá en la página de inicio de sesión')
        ],
        frecuencia="Baja",
        rendimiento="Alto",
        importancia="Alta",
        urgencia="Alta",
        estado="Realizado",
        estabilidad="Alta",
        comentarios="El token de autenticación se guardará en el cliente, permitiendo al usuario mantener su sesión iniciada sin tener que repetir el proceso cada vez"
    ),
    CasoDeUso(
        titulo="Modificar Contraseña",
        actores="Usuario",
        tipo="Primario",
        requisitos="RF-20",
        casoDeUso="",
        precondicion="",
        postcondicion="La contraseña del usuario se habrá actualizado en la base de datos",
        proposito="Modificar la contraseña del usuario",
        resumen="Un usuario podrá modificar su contraseña desde la página de usuario",
        flujo=[
            Flujo('1','Usuario: Entrará al panel de gestión de usuario','',''),
            Flujo('2','Usuario: Rellenará el formulario de cambio de contraseña especificando su contraseña actual y la contraseá nueva','',''),
            Flujo('','','3','Se valida que la contraseña proporcionada sea correcta'),
            Flujo('','','4','Se modifica la contraseña del usuario en la base de datos'),
            Flujo('5','Usuario: Recibirá una respuesta exitosa del sistema','',''),
        ],
        flujoAlterno=[
            FlujoAlterno('3a','Si la contraseña actual proporcionada no es correcta se devolverá un mensaje de error al usuario')
        ],
        frecuencia="Muy baja",
        rendimiento="Alta",
        importancia="Alta",
        urgencia="Baja",
        estado="Realizado",
        estabilidad="Alta",
        comentarios=""
    ),
    CasoDeUso(
        titulo="Cerrar Sesión",
        actores="Usuario, Visitante(Secundario)",
        tipo="Primario",
        requisitos="RF-6",
        casoDeUso="",
        precondicion="",
        postcondicion="El rol del actor pasará a ser Visitante",
        proposito="Permitir cerrar sesión al Usuario",
        resumen="El usuario cerrará sesión en la aplicación",
        flujo=[
            Flujo('1','Usuario: Interactuará con el botón de cierre de sesión','',''),
            Flujo('','','2','Se borrará del cliente el token de autenticación'),
            Flujo('','','3','Se invalidará el token de autenticación en la base de datos'),
            Flujo('4','Visitante: Se le redigirá a la página de inicio de sesión','',''),
        ],
        flujoAlterno=[
            FlujoAlterno('','')
        ],
        frecuencia="Baja",
        rendimiento="Alto",
        importancia="Alta",
        urgencia="Baja",
        estado="Realizado",
        estabilidad="Alta",
        comentarios="El token de autenticación se borrará del cliente"
    ),
    CasoDeUso(
        titulo="Subir Dataset",
        actores="Usuario",
        tipo="Primario",
        requisitos="RF-7, RNF-2",
        casoDeUso="",
        precondicion="El usuario no tiene subido ese dataset en el sistema",
        postcondicion="Se subirá el dataset al sistema",
        proposito="El usuario podrá subir un dataset al sistema",
        resumen="El usuario seleccionará subir un nuevo dataset al sistema, ya sea desde un fichero local o cargando el dataset desde HuggingFace",
        flujo=[
            Flujo('1','Usuario: Seleccionará añadir un nuevo dataset','',''),
            Flujo('2','Usuario: Seleccionará el dataset que quiera subir','',''),
            Flujo('','','3','Se creará una nueva entrada en la base de datos con el dataset creado'),
            Flujo('4','Usuario: Recibirá una respuesta exitosa','',''),
        ],
        flujoAlterno=[
            FlujoAlterno('2a','El usuario podrá subir el dataset desde un fichero local, pudiendo marcar este como privado'),
            FlujoAlterno('2b','El usuario podrá buscar un dataset existente en HuggingFace y subirlo al sistema'),
            FlujoAlterno('3a','Si el dataset se ha cargado desde un fichero local se guardará en el servidor'),
        ],
        frecuencia="Media",
        rendimiento="Medio",
        importancia="Alta",
        urgencia="Alta",
        estado="Realizado",
        estabilidad="Alta",
        comentarios=""
    ),
    CasoDeUso(
        titulo="Borrar Dataset",
        actores="Usuario Propietario, Administrador",
        tipo="Primario",
        requisitos="RF-15",
        casoDeUso="CU-02",
        precondicion="El dataset tiene que existir en el sistema",
        postcondicion="Usuario autenticado",
        proposito="Permitir acceso seguro",
        resumen="Caso de uso para autenticación",
        flujo=[
            Flujo('','','',''),
        ],
        flujoAlterno=[
            FlujoAlterno('',''),
        ],
        frecuencia="Alta",
        rendimiento="Menos de 2 segundos",
        importancia="Alta",
        urgencia="Alta",
        estado="Realizado",
        estabilidad="Alta",
        comentarios="Funcionalidad crítica"
    ),
    CasoDeUso(
        titulo="Listar Datasets",
        actores="Usuario",
        tipo="Primario",
        requisitos="CU000",
        casoDeUso="CU001",
        precondicion="Aplicación instalada",
        postcondicion="Usuario autenticado",
        proposito="Permitir acceso seguro",
        resumen="Caso de uso para autenticación",
        flujo=[
            Flujo('','','',''),
        ],
        flujoAlterno=[
            FlujoAlterno('',''),
        ],
        frecuencia="Alta",
        rendimiento="Menos de 2 segundos",
        importancia="Alta",
        urgencia="Alta",
        estado="Realizado",
        estabilidad="Alta",
        comentarios="Funcionalidad crítica"
    ),
    CasoDeUso(
        titulo="Inspeccionar Dataset",
        actores="Usuario",
        tipo="Primario",
        requisitos="CU000",
        casoDeUso="CU001",
        precondicion="Aplicación instalada",
        postcondicion="Usuario autenticado",
        proposito="Permitir acceso seguro",
        resumen="Caso de uso para autenticación",
        flujo=[
            Flujo('','','',''),
        ],
        flujoAlterno=[
            FlujoAlterno('',''),
        ],
        frecuencia="Alta",
        rendimiento="Menos de 2 segundos",
        importancia="Alta",
        urgencia="Alta",
        estado="Realizado",
        estabilidad="Alta",
        comentarios="Funcionalidad crítica"
    ),
    CasoDeUso(
        titulo="Subir Modelo",
        actores="Usuario",
        tipo="Primario",
        requisitos="CU000",
        casoDeUso="CU001",
        precondicion="Aplicación instalada",
        postcondicion="Usuario autenticado",
        proposito="Permitir acceso seguro",
        resumen="Caso de uso para autenticación",
        flujo=[
            Flujo('','','',''),
        ],
        flujoAlterno=[
            FlujoAlterno('',''),
        ],
        frecuencia="Alta",
        rendimiento="Menos de 2 segundos",
        importancia="Alta",
        urgencia="Alta",
        estado="Realizado",
        estabilidad="Alta",
        comentarios="Funcionalidad crítica"
    ),
    CasoDeUso(
        titulo="Borrar Modelo",
        actores="Usuario",
        tipo="Primario",
        requisitos="CU000",
        casoDeUso="CU001",
        precondicion="Aplicación instalada",
        postcondicion="Usuario autenticado",
        proposito="Permitir acceso seguro",
        resumen="Caso de uso para autenticación",
        flujo=[
            Flujo('','','',''),
        ],
        flujoAlterno=[
            FlujoAlterno('',''),
        ],
        frecuencia="Alta",
        rendimiento="Menos de 2 segundos",
        importancia="Alta",
        urgencia="Alta",
        estado="Realizado",
        estabilidad="Alta",
        comentarios="Funcionalidad crítica"
    ),
    CasoDeUso(
        titulo="Listar Modelos",
        actores="Usuario",
        tipo="Primario",
        requisitos="CU000",
        casoDeUso="CU001",
        precondicion="Aplicación instalada",
        postcondicion="Usuario autenticado",
        proposito="Permitir acceso seguro",
        resumen="Caso de uso para autenticación",
        flujo=[
            Flujo('','','',''),
        ],
        flujoAlterno=[
            FlujoAlterno('',''),
        ],
        frecuencia="Alta",
        rendimiento="Menos de 2 segundos",
        importancia="Alta",
        urgencia="Alta",
        estado="Realizado",
        estabilidad="Alta",
        comentarios="Funcionalidad crítica"
    ),
    CasoDeUso(
        titulo="Realizar Clasificación",
        actores="Usuario",
        tipo="Primario",
        requisitos="CU000",
        casoDeUso="CU001",
        precondicion="Aplicación instalada",
        postcondicion="Usuario autenticado",
        proposito="Permitir acceso seguro",
        resumen="Caso de uso para autenticación",
        flujo=[
            Flujo('','','',''),
        ],
        flujoAlterno=[
            FlujoAlterno('',''),
        ],
        frecuencia="Alta",
        rendimiento="Menos de 2 segundos",
        importancia="Alta",
        urgencia="Alta",
        estado="Realizado",
        estabilidad="Alta",
        comentarios="Funcionalidad crítica"
    ),
    CasoDeUso(
        titulo="Borrar Clasificación",
        actores="Usuario",
        tipo="Primario",
        requisitos="CU000",
        casoDeUso="CU001",
        precondicion="Aplicación instalada",
        postcondicion="Usuario autenticado",
        proposito="Permitir acceso seguro",
        resumen="Caso de uso para autenticación",
        flujo=[
            Flujo('','','',''),
        ],
        flujoAlterno=[
            FlujoAlterno('',''),
        ],
        frecuencia="Alta",
        rendimiento="Menos de 2 segundos",
        importancia="Alta",
        urgencia="Alta",
        estado="Realizado",
        estabilidad="Alta",
        comentarios="Funcionalidad crítica"
    ),
    CasoDeUso(
        titulo="Listar Clasificaciones",
        actores="Usuario",
        tipo="Primario",
        requisitos="CU000",
        casoDeUso="CU001",
        precondicion="Aplicación instalada",
        postcondicion="Usuario autenticado",
        proposito="Permitir acceso seguro",
        resumen="Caso de uso para autenticación",
        flujo=[
            Flujo('','','',''),
        ],
        flujoAlterno=[
            FlujoAlterno('',''),
        ],
        frecuencia="Alta",
        rendimiento="Menos de 2 segundos",
        importancia="Alta",
        urgencia="Alta",
        estado="Realizado",
        estabilidad="Alta",
        comentarios="Funcionalidad crítica"
    ),
    CasoDeUso(
        titulo="Ver Resultados",
        actores="Usuario",
        tipo="Primario",
        requisitos="CU000",
        casoDeUso="CU001",
        precondicion="Aplicación instalada",
        postcondicion="Usuario autenticado",
        proposito="Permitir acceso seguro",
        resumen="Caso de uso para autenticación",
        flujo=[
            Flujo('','','',''),
        ],
        flujoAlterno=[
            FlujoAlterno('',''),
        ],
        frecuencia="Alta",
        rendimiento="Menos de 2 segundos",
        importancia="Alta",
        urgencia="Alta",
        estado="Realizado",
        estabilidad="Alta",
        comentarios="Funcionalidad crítica"
    ),
]
