# Generated by Django 5.1.3 on 2025-05-06 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0002_alter_dataset_upload_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationProcess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('UNQUEUE', 'UNQUEUE'), ('PROCESSING', 'PROCESSING'), ('FINISHED', 'FINISHED'), ('ERROR', 'ERROR')], default='UNQUEUE', max_length=255)),
                ('model_name', models.CharField(max_length=255)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasets.dataset')),
            ],
        ),
    ]
