# Generated by Django 5.1.3 on 2025-05-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifications', '0002_alter_classificationprocess_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificationprocess',
            name='status',
            field=models.CharField(choices=[('IN_QUEUE', 'IN_QUEUE'), ('PROCESSING', 'PROCESSING'), ('FINISHED', 'FINISHED'), ('ERROR', 'ERROR')], default='IN_QUEUE', max_length=255),
        ),
    ]
