# Generated by Django 5.1.3 on 2025-06-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifications', '0003_alter_classificationprocess_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificationprocess',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
