# Generated by Django 5.1.3 on 2025-06-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifications', '0005_classificationprocess_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationprocess',
            name='parameters',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
